disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Nick Moyer | Software Engineer"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_dark.png"
secondaryLogo = "logo_light.png"

[params.author]
name = "Nick Moyer"
image = "profile.png"
headline = "Backend Software Engineer | Go, Python, Typescript | Healthcare Interoperability (FHIR) | APIs & AI Integration"
bio = "Software Engineer with a passion for architecting scalable backends, AI-driven automation, and FHIR interoperability."
links = [
    { github = "https://github.com/nick-moyer" },
    { linkedin = "https://www.linkedin.com/in/npmoyer" },
    { bluesky = "https://bsky.app/profile/nickmoyer.dev" },
    { goodreads = "https://www.goodreads.com/nick-moyer" },
    { email = "mailto:hello@nickmoyer.dev" },
]