disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Nick Moyer | Software Engineer"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_dark.png"
secondaryLogo = "logo_light.png"

[params.author]
name = "Nick Moyer"
image = "profile.png"
headline = "Backend Software Engineer | Python, Node, Go, APIs, Data & AI | Mission-driven and always curious"
bio = "Software Engineer specializing in intelligent backend architecture, AI pipeline integration and EHR (FHIR) data."
links = [
    { github = "https://github.com/nick-moyer" },
    { linkedin = "https://www.linkedin.com/in/npmoyer" },
    { email = "mailto:hello@nickmoyer.dev" },
]